
openapi: "3.0.0"

info:
  title: Hello World
  version: "1"
servers:
  - url: http://localhost:9090/v1

paths:
  /greeting:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: myapp.controller.hello_world_controller.get_hello_world
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello world!"
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: myapp.controller.hello_world_controller.post_greeting
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello world!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "world"