
openapi: "3.0.0"

info:
  title: Hello World
  version: "1"
servers:
  - url: http://localhost:9090/v1

paths:
  /greeting:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: myapp.controller.hello_world_controller.get_hello_world
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello world!"
    post:
      summary: Add student
      description: Generates a id number.
      operationId: myapp.controller.hello_world_controller.post_greeting
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
                  name: 
                    type: string
                  lastname: 
                    type: string
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        name: 
          type: string
        lastname: 
          type: string